x-base_service: &base_service
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
    # runtime: nvidia
    # security_opt:
    #   - label=type:nvidia_container_t

services:
  download:
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    devices:
      - /dev/dri
      - /dev/kfd
    ipc:
      - host
