# UI defaults configuration file. It is automatically loaded if located at configs/webui/webui_streamlit.yaml.
general:
  gpu: 0
  outdir: /outputs
  ckpt: "/cache/models/model.ckpt"
  fp:
    name: "embeddings/alex/embeddings_gs-11000.pt"
  GFPGAN_dir: "./src/gfpgan"
  RealESRGAN_dir: "./src/realesrgan"
  RealESRGAN_model: "RealESRGAN_x4plus"
  outdir_txt2img: /outputs/txt2img-samples
  outdir_img2img: /outputs/img2img-samples
  gfpgan_cpu: False
  esrgan_cpu: False
  extra_models_cpu: False
  extra_models_gpu: False
  save_metadata: True
  skip_grid: False
  skip_save: False
  grid_format: "jpg:95"
  save_format: "png"
  n_rows: -1
  no_verify_input: False
  no_half: False
  precision: "autocast"
  optimized: False
  optimized_turbo: False
  update_preview: True
  update_preview_frequency: 1

txt2img:
  prompt:
  height: 512
  width: 512
  cfg_scale: 5.0
  seed: ""
  batch_count: 1
  batch_size: 1
  sampling_steps: 50
  default_sampler: "k_lms"
  separate_prompts: False
  normalize_prompt_weights: True
  save_individual_images: True
  save_grid: True
  group_by_prompt: True
  save_as_jpg: False
  use_GFPGAN: True
  use_RealESRGAN: True
  RealESRGAN_model: "RealESRGAN_x4plus"
  variant_amount: 0.0
  variant_seed: ""

img2img:
  prompt:
  sampling_steps: 50
  # Adding an int to toggles enables the corresponding feature.
  # 0: Create prompt matrix (separate multiple prompts using |, and get all combinations of them)
  # 1: Normalize Prompt Weights (ensure sum of weights add up to 1.0)
  # 2: Loopback (use images from previous batch when creating next batch)
  # 3: Random loopback seed
  # 4: Save individual images
  # 5: Save grid
  # 6: Sort samples by prompt
  # 7: Write sample info files
  # 8: jpg samples
  # 9: Fix faces using GFPGAN
  # 10: Upscale images using Real-ESRGAN
  sampler_name: k_lms
  denoising_strength: 0.45
  # 0: Keep masked area
  # 1: Regenerate only masked area
  mask_mode: 0
  # 0: Just resize
  # 1: Crop and resize
  # 2: Resize and fill
  resize_mode: 0
  # Leave blank for random seed:
  seed: ""
  ddim_eta: 0.0
  cfg_scale: 5.0
  batch_count: 1
  batch_size: 1
  height: 512
  width: 512
  # Textual inversion embeddings file path:
  fp: ""
  loopback: True
  random_seed_loopback: True
  separate_prompts: False
  normalize_prompt_weights: True
  save_individual_images: True
  save_grid: True
  group_by_prompt: True
  save_as_jpg: False
  use_GFPGAN: True
  use_RealESRGAN: True
  RealESRGAN_model: "RealESRGAN_x4plus"
  variant_amount: 0.0
  variant_seed: ""

gfpgan:
  strength: 100
