version: '3.9'

services:
  model:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ../cache:/cache
      - ../output:/output
      - ../models:/models
      - ./config.json:/docker/config.json
    environment:
      - CLI_ARGS=--medvram --opt-split-attention
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
