name: Build Image

on: [push]

# TODO: how to cache intermediate images?
jobs:
  build_hlky:
    runs-on: ubuntu-latest
    name: hlky
    steps:
      - uses: actions/checkout@v3
      - run: docker compose --profile hlky build --progress plain
  build_AUTOMATIC1111:
    runs-on: ubuntu-latest
    name: AUTOMATIC1111
    steps:
      - uses: actions/checkout@v3
      - run: docker compose --profile auto  build --progress plain
  build_lstein:
    runs-on: ubuntu-latest
    name: lstein
    steps:
      - uses: actions/checkout@v3
      - run: docker compose --profile lstein build --progress plain
