name: Build Xformers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: pytorch/manylinux-cuda113
    container:
      image: debian:stable-slim
      env:
        CU_VERSION: cu113
        PYTHON_VERSION: "3.10"
        PYTORCH_VERSION: "1.12"
    steps:
      - run: |
          git clone https://github.com/facebookresearch/xformers x
          cd x
          ./packaging/build_wheel.sh
