name: Build Images

on:
  push:
    branches: 
      - master
      - docker-build-and-push
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        profile: [auto , sygil , invoke ,comfy , download]
        include:
          - profile: auto
            dockertag: "sd-auto:51"
            dockerhubtag: "sd-auto:latest"
        # dockertag: ["sd-auto:51","sd-sygil:16", "sd-invoke:27", "sd-comfy:1" , "sd-download:51"]
        # dockerhubtag: [sd-auto , sd-sygil , sd-invoke ,sd-comfy , sd-download]
          # - auto
          # - sygil
          # - invoke
          # - comfy
          # - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
    #   # - uses: actions/checkout@v3
    #   # - run: docker compose --profile ${{ matrix.profile }} build --progress plain
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{secrets.DOCKERHUB_USERNAME}}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "docker build is ok." ${{matrix.profile}} ${{matrix.dockertag}} ${{matrix.dockerhubtag}}
          


