name: Build Images

on:
  push:
    branches: 
      - master
      - docker-build-and-push
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        profile: [download]
        include:
          # - profile: auto
          #   dockertag: "sd-auto:51"
          #   dockerhubtag: "sd-auto"
          # - profile: sygil
          #   dockertag: "sd-sygil:16"
          #   dockerhubtag: "sd-sygil"
          # - profile: invoke
          #   dockertag: "sd-invoke:27"
          #   dockerhubtag: "sd-invoke"
          # - profile: comfy
          #   dockertag: "sd-comfy:1"
          #   dockerhubtag: "sd-comfy"
          - profile: download
            dockertag: "sd-download:51"
            dockerhubtag: "sd-downlaod"
        # dockertag: ["sd-auto:51","sd-sygil:16", "sd-invoke:27", "sd-comfy:1" , "sd-download:51"]
        # dockerhubtag: [sd-auto , sd-sygil , sd-invoke ,sd-comfy , sd-download]
          # - auto
          # - sygil
          # - invoke
          # - comfy
          # - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - run: echo env ${{env.DOCKERHUB_USERNAME}}  vars ${{vars.DOCKERHUB_USERNAME}} 
      - uses: actions/checkout@v3
      - run: docker compose --profile ${{ matrix.profile }} build --progress plain
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "docker build is ok." ${{matrix.profile}} ${{matrix.dockertag}} ${{matrix.dockerhubtag}}
      - run: echo env ${{env.DOCKERHUB_USERNAME}}  vars ${{vars.DOCKERHUB_USERNAME}} 
      - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - run: echo ${SHORT_SHA}
      - run: docker image ls
      - run: docker tag ${{matrix.dockertag}} ${{vars.DOCKERHUB_USERNAME}}/${{matrix.dockerhubtag}}:latest
      - run: docker tag ${{matrix.dockertag}} ${{vars.DOCKERHUB_USERNAME}}/${{matrix.dockerhubtag}}:${SHORT_SHA}
      - run: docker image ls
      # - run: echo docker image push --all-tags ${{vars.DOCKERHUB_USERNAME}}/${{matrix.dockerhubtag}}
   


