name: Build Image

on: [push]

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # better caching?
      - run: docker compose --profile hlky build --progress plain
      - run: docker compose --profile auto  build --progress plain
      - run: docker compose --profile lstein build --progress plain
