name: Build Images

on:
  push:
    branches: master
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - sygil
          - invoke
          - comfy
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            auto:
              - 'services/auto/**'
            sygil:
              - 'services/sygil/**'
            invoke:
              - 'services/invoke/**'
            comfy:
              - 'services/comfy/**'

      - run: docker compose --profile ${{ matrix.profile }} build --progress plain
        if: github.ref == 'refs/heads/master' || steps.changes.outputs.${{ matrix.profile }} == 'true'
