name: Check executable

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check all sh
    steps:
      - uses: actions/checkout@v3
      - shell: /bin/bash -ce
        run: |
          shopt -s globstar;
          for file in **/*.sh; do
              if [ -f "${file}" ] && [ -r "${file}" ] && [ ! -x "${file}" ]; then
                  echo "$file" is not executable;
                  exit 1;
              fi
          done
